### ISSUE TITLE
Unable to get response for raw data query  for elasticsearch configuration in opensearch

### ISSUE THREAD

**Issue by jishnunand** [grafana/opensearch-datasource#414]
**What happened**:
Opensearch not providing results when selecting raw data. I have connected my opensearch with elastic server and trying to get data using raw Data in Metric. Same Raw data works in Elasticsearch plugin.

Getting data for metric count but not with Raw Data metric.
**What you expected to happen**:
Its should provide a response for that particular query

**Environment**:
- Grafana version: 9.5.14
- Elastic Search version: 6.5.4
- Opensearch Plugin version:2.13.1

![WhatsApp Image 2024-07-05 at 21 52 13](https://github.com/grafana/opensearch-datasource/assets/9170609/65fd73fc-ba89-448c-b2bc-14ca7c97df47)
![WhatsApp Image 2024-07-05 at 21 52 15](https://github.com/grafana/opensearch-datasource/assets/9170609/d361eee5-ecaf-439c-807f-fd2768ac39b7)
![WhatsApp Image 2024-07-05 at 21 52 16](https://github.com/grafana/opensearch-datasource/assets/9170609/0e0cf396-d527-49b6-aa98-73faea655950)
![WhatsApp Image 2024-07-05 at 21 55 15](https://github.com/grafana/opensearch-datasource/assets/9170609/b6987491-173c-4594-a437-bb2d1db8aefa)

**Comment by njvrzm** [comment]
Hello, and thanks for the report! This issue was fixed in a recent release, but in testing that I found another bug that would come up with the version of Elasticsearch you're using. I have a PR open to fix that (#415). Once that's merged I'll release a new version of the plugin and let you know here so you can update yours for the fix.

**Comment by jishnunand** [comment]
When can we expect the release of these changes?
I have checked for release notes and not able to find any changes related to this. The PR got merged but still not new plugin release with new changes.

**Comment by njvrzm** [comment]
The fix has been released: https://github.com/grafana/opensearch-datasource/releases/tag/v2.17.1. Please let us know if it resolves your issue.
